import { Names } from "../pom/names";
import { Staff } from "../pom/staff";
import { getText } from "../read-file";

const NORMALISED_CLUBS: Record<string, string> = {
  "Birmingham City": "Birmingham",
  "Blackburn Rovers": "Blackburn",
  "Bolton Wanderers": "Bolton",
  "AFC Bournemouth": "Bournemouth",
  "Bradford City": "Bradford",
  "Brighton and Hove Albion": "Brighton",
  "Bristol City": "Bristol C",
  "Bristol Rovers": "Bristol R",
  "Crystal Palace": "C.Palace",
  "Cambridge United": "Cambridge",
  "Cardiff City": "Cardiff",
  "Charlton Athletic": "Charlton",
  "Chester City": "Chester",
  Chesterfield: "Chesterfield",
  "Colchester United": "Colchester",
  "Coventry City": "Coventry",
  "Crewe Alexandra": "Crewe",
  "Derby County": "Derby",
  "Doncaster Rovers": "Doncaster",
  "Exeter City": "Exeter",
  "Grimsby Town": "Grimsby",
  "Hartlepool United": "Hartlepool",
  "Huddersfield Town": "Huddersfld",
  "Hull City": "Hull",
  "Ipswich Town": "Ipswich",
  "Leeds United": "Leeds",
  "Leicester City": "Leicester",
  "Leyton Orient": "Leyton O",
  "Luton Town": "Luton",
  "Manchester City": "Man City",
  "Manchester United": "Man Utd",
  Middlesbrough: "Middlesboro",
  "Nottingham Forest": "N.Forest",
  "Newcastle United": "Newcastle",
  "Notts County": "Notts C",
  "Norwich City": "Norwich",
  "Oldham Athletic": "Oldham",
  "Oxford United": "Oxford",
  "Peterborough United": "Peterboro",
  "Plymouth Argyle": "Plymouth",
  "Preston North End": "Preston",
  "Queens Park Rangers": "Q.P.R.",
  "Rotherham United": "Rotherham",
  "Scunthorpe United": "Scunthorpe",
  "Sheffield United": "Sheff Utd",
  "Sheffield Wednesday": "Sheff Wed",
  "Southend United": "Southend",
  "Stockport County": "Stockport",
  "Stoke City": "Stoke",
  "Swansea City": "Swansea",
  "Swindon Town": "Swindon",
  "Torquay United": "Torquay",
  "Tottenham Hotspur": "Tottenham",
  "Tranmere Rovers": "Tranmere",
  "West Bromwich Albion": "W.B.A.",
  "West Ham United": "West Ham",
  "Wolverhampton Wanderers": "Wolves",
  "Wycombe Wanderers": "Wycombe",
  "York City": "York",
};

const FIRST_NAMES: Record<string, string> = {
  Zbigniew: "Zbignew",
  Ruggiero: "Rugg",
  "Jean-Luc": "Jean",
  Wlademar: "Wlad",
  Sscrates: "Socrates",
  Salvatore: "Salv",
  Francesco: "Franc",
  "Josi Ramsn": "Josi",
  Gianfranco: "Franco",
  Sebastiano: "Seb",
  "Jean-Marie": "Jean",
  "Jorge Luis": "Jorge",
  "Ramsn Marma": "Ramon",
  "Paulo Futre": "Paulo",
  "Abel Resino": "Abel",
  "Jean-Michel": "Jean",
  "Hugo Sanchez": "Hugo",
  "Vmctor Muqoz": "Victor",
  "Josi Antonio": "Josi",
  "Miguel Angel": "Miguel",
  "Quique Ramos": "Quique",
  "Pietro Paolo": "Paolo",
  "Julio Romero": "Julio",
  "Pogus Cassius": "Pogus",
  "Julio Salinas": "Julio",
  "Quique Setiin": "Quique",
  "Jean-Philippe": "Jean",
  "Renato Gazcho": "Renato",
  "John Okechukwu": "John",
  "Francisco Josi": "Franc",
  Francsco: "Franc",
  "Miguel Portlan": "Miguel",
  "Patrick Anthony": "Patrick",
  "Miguel Gonzalez": "Miguel",
  "Miguel Bernardo": "Miguel",
  "Salvador Garcia": "Salv",
  "Francisco Ernani": "Franc",
  "Eusebio Sacristan": "Eusebio",
  "Juan Manuel Martinez": "Juan",
  Beniamino: "Beni",
  "J|rgen": "Jurgen",
  Iric: "Eric",
  "Faustino Asprilla": "Tino",
  Faustino: "Tino",
  "Gustavo Poyet": "Gustavo",
  "Juan Josi Sanchez": "Juan",
  "Santiago Aragsn": "Santi",
  Santiago: "Santi",
  "Jeszs Angel": "Jeszs",
  Alberigo: "Alberico",
  Fernando: "Nando",
  "Ole Gunnar": "Ole",
  Christopher: "Chris",
  Osvaldo: "Ossie",
  Sigurpur: "Sigur",
  Ugochuku: "Ugo",
  Fabrizio: "Fabrizio  ",
  Vincenzo: "Vincenzo   ",
  Darron: "Darren",
  Gudjon: "Gujon",
};

const SURNAMES: Record<string, string> = {
  "Rhoades-Brown": "Rhoades",
  "Julio Alberto": "Alberto",
  "Gsmez Colomer": "Gsmez",
  "Arteche Gsmez": "Gsmez",
  "Martmn Vazquez": "Vazquez",
  "Romero Insfran": "Insfran",
  "Parra Fernandez": "Fernandez",
  "Pfl|gler": "Pflugler",
  Matthdus: "Matthaus",
  "M|ller": "Muller",
  Solskjfr: "Solskjaer",
  "Asprilla Hinestroza": "Asprilla",
  "Poyet Dominguez": "Poyet",
  "Lspez Lspez": "Lopez",
  Mvller: "Muller",
  Jsnsson: "Jonsson",
};

export const getNormalisedName = (name: string): string => FIRST_NAMES[name] || name;
export const getNormalisedSurname = (name: string): string => SURNAMES[name] || name;
export const getNormalisedClub = (name: string): string => NORMALISED_CLUBS[name] || name;

export const getNames = (
  player: Staff,
  firstNames: Names[],
  surnames: Names[],
  commonNames: Names[],
  nation: string,
): { firstName: string; surname: string } => {
  const firstName = getText(firstNames[player.FirstName].name);
  const surname = getText(surnames[player.SecondName].name);
  const commonName = player.CommonName > 0 ? getText(commonNames[player.CommonName].name) : null;

  // Let Brazilian players have a single name
  if (nation === "Brazil" && commonName && commonName.split(" ").length === 1)
    return { firstName: "..", surname: getNormalisedName(commonName) };

  return {
    firstName: getNormalisedName(commonName && surname !== commonName ? commonName : firstName),
    surname: getNormalisedSurname(surname),
  };
};
