import { Names } from "../pom/names";
import { Staff } from "../pom/staff";
import { getText } from "../read-file";

const NORMALISED_CLUBS: Record<string, string> = {
  "Birmingham City": "Birmingham",
  "Blackburn Rovers": "Blackburn",
  "Bolton Wanderers": "Bolton",
  "AFC Bournemouth": "Bournemouth",
  "Bradford City": "Bradford",
  "Brighton and Hove Albion": "Brighton",
  "Bristol City": "Bristol C",
  "Bristol Rovers": "Bristol R",
  "Crystal Palace": "C.Palace",
  "Cambridge United": "Cambridge",
  "Cardiff City": "Cardiff",
  "Charlton Athletic": "Charlton",
  "Chester City": "Chester",
  Chesterfield: "Chesterfield",
  "Colchester United": "Colchester",
  "Coventry City": "Coventry",
  "Crewe Alexandra": "Crewe",
  "Derby County": "Derby",
  "Doncaster Rovers": "Doncaster",
  "Exeter City": "Exeter",
  "Grimsby Town": "Grimsby",
  "Hartlepool United": "Hartlepool",
  "Huddersfield Town": "Huddersfld",
  "Hull City": "Hull",
  "Ipswich Town": "Ipswich",
  "Leeds United": "Leeds",
  "Leicester City": "Leicester",
  "Leyton Orient": "Leyton O",
  "Luton Town": "Luton",
  "Manchester City": "Man City",
  "Manchester United": "Man Utd",
  Middlesbrough: "Middlesboro",
  "Nottingham Forest": "N.Forest",
  "Newcastle United": "Newcastle",
  "Notts County": "Notts C",
  "Norwich City": "Norwich",
  "Oldham Athletic": "Oldham",
  "Oxford United": "Oxford",
  "Peterborough United": "Peterboro",
  "Plymouth Argyle": "Plymouth",
  "Preston North End": "Preston",
  "Queens Park Rangers": "Q.P.R.",
  "Rotherham United": "Rotherham",
  "Scunthorpe United": "Scunthorpe",
  "Sheffield United": "Sheff Utd",
  "Sheffield Wednesday": "Sheff Wed",
  "Southend United": "Southend",
  "Stockport County": "Stockport",
  "Stoke City": "Stoke",
  "Swansea City": "Swansea",
  "Swindon Town": "Swindon",
  "Torquay United": "Torquay",
  "Tottenham Hotspur": "Tottenham",
  "Tranmere Rovers": "Tranmere",
  "West Bromwich Albion": "W.B.A.",
  "West Ham United": "West Ham",
  "Wolverhampton Wanderers": "Wolves",
  "Wycombe Wanderers": "Wycombe",
  "York City": "York",
};

const FIRST_NAMES: Record<number, Record<string, string>> = {
  82: {
    "Daniel Passarella": "Daniel",
    "Mario Kempes": "Mario",
    "Diego Maradona": "Diego",
    "Gabriel Batistuta": "Gabriel",
    "Toninho Cerezo": "Toninho",
    "Faustino Asprilla": "Tino",
    "Reni Higuita": "Reni",
    "Emilio Butragueqo": "Emilio",
    "Ruben Sosa": "Ruben",
    "Carlos Alberto": "Carlos",
    "Hugo Sanchez": "Hugo",
    "Fernando Hierro": "Fernando",
    "Miguel Angel Nadal": "Miguel",
    Migueli: "Miguel",
    Rvber: "Rober",
    "Horst-Dieter": "Horst",
    "Ossie Ardiles": "Ossie",
    "Rafael Villazan": "Rafael",
    "Josi Mari Bakero": "Josi",
    "Txiki Begiristain": "Txiki",
    "Sergio Batista": "Sergio",
    "Sscar Ruggeri": "Oscar",
    "Andoni Zubizarreta": "Andoni",
    "Rafael Zuvirma": "Rafael",
    "Jean-Pierre": "J-Pierre",
    "Karl-Heinz": "Karl-H",
    "Manuel Sanchms": "Manuel",
    "Ricky Villa": "Ricky",
    Francesco: "Franc",
    Gheorghe: "Gheorghe   ",
    Gianfranco: "Franco",
    Melvyn: "Mel",
    Salvatore: "Salv",
    Peli: "Pele ",
    Doug: "Doug ",
    Ram: "Ram ",
  },
  86: {},
  88: {
    Zbigniew: "Zbignew",
    Ruggiero: "Rugg",
    "Jean-Luc": "Jean",
    Wlademar: "Wlad",
    Salvatore: "Salv",
    Francesco: "Franc",
    "Josi Ramsn": "Josi",
    Gianfranco: "Franco",
    Sebastiano: "Seb",
    "Jean-Marie": "Jean",
    "Jorge Luis": "Jorge",
    "Ramsn Marma": "Ramon",
    "Paulo Futre": "Paulo",
    "Abel Resino": "Abel",
    "Jean-Michel": "Jean",
    "Hugo Sanchez": "Hugo",
    "Vmctor Muqoz": "Victor",
    "Josi Antonio": "Josi",
    "Miguel Angel": "Miguel",
    "Quique Ramos": "Quique",
    "Pietro Paolo": "Paolo",
    "Julio Romero": "Julio",
    "Pogus Cassius": "Pogus",
    "Julio Salinas": "Julio",
    "Quique Setiin": "Quique",
    "Jean-Philippe": "Jean",
    "Renato Gazcho": "Renato",
    "John Okechukwu": "John",
    "Francisco Josi": "Franc",
    Francsco: "Franc",
    "Miguel Portlan": "Miguel",
    "Patrick Anthony": "Patrick",
    "Miguel Gonzalez": "Miguel",
    "Miguel Bernardo": "Miguel",
    "Salvador Garcia": "Salv",
    "Francisco Ernani": "Franc",
    "Eusebio Sacristan": "Eusebio",
    "Juan Manuel Martinez": "Juan",
    "Gabriel Omar": "Batistuta",
    Beniamino: "Beni",
    Iric: "Eric",
    "Faustino Asprilla": "Tino",
    Faustino: "Tino",
    "Gustavo Poyet": "Gustavo",
    "Juan Josi Sanchez": "Juan",
    "Santiago Aragsn": "Santi",
    Santiago: "Santi",
    "Jeszs Angel": "Jeszs",
    Alberigo: "Alberico",
    Fernando: "Nando",
    "Ole Gunnar": "Ole",
    Christopher: "Chris",
    Osvaldo: "Ossie",
    Sigurpur: "Sigur",
    Ugochuku: "Ugo",
    Fabrizio: "Fabrizio  ",
    Vincenzo: "Vincenzo",
    Darron: "Darren",
    Gudjon: "Gujon",
    "Giovane Ilber": "Giovane",
    Pierluigi: "Luigi",
    Massimiliano: "Massi",
  },
  90: {
    "Roberto Carlos": "Roberto",
    "Claudio Taffarel": "Claudio",
    "Ricardo Gomes": "Ricardo",
    "Rui Barros": "Rui",
    Gianfranco: "Franco",
    Rudi: "Rudi ",
    Figo: "Figo ",
    Mats: "Mats ",
    Ilie: "Ilie ",
    Hugo: "Hugo ",
    Jock: "Jock ",
    Theo: "Theo ",
    "Jean-Marc": "Jean",
    Daniele: "Daniele",
    Osvaldo: "Ossie",
    Zvonimir: "Zvimir",
    Gianluigi: "Luigi",
    Pierluigi: "Luigi",
    Pierliugi: "Luigi",
    Giancarlo: "Gian ",
    Oleksandr: "Oleks",
    Aldo: "Aldo ",
    Gheorghe: "George",
  },
  98: {},
};

const SURNAMES: Record<number, Record<string, string>> = {
  82: {
    "Alberto Passarella": "Passarella",
    "Kempes Chiodi": "Kempes",
    "Maradona Franco": "Maradona",
    "Omar Batistuta": "Batistuta",
    "Carlos Cerezo": "Cerezo",
    "Asprilla Hinestroza": "Asprilla",
    "Higuita Zapata": "Higuita",
    "Butragueqo Santos": "Butragueno",
    "Nadal Homar": "Nadal",
    "Ruiz Hierro": "Hierro",
    "Sanchez Marquez": "Sanchez",
    "Alberto Torres": "Alberto",
    "Sosa Arzaiz": "Sosa",
    "Cisar Ardiles": "Ardiles",
    "Villazan Guillin": "Villazan",
    "van Breukelen": "v. Breukelen",
    "Daniel Batista": "Batista",
    "Ruggeri Zocola": "Ruggeri",
    "Lozano Bohsrquez": "Bohsrquez",
    "Alexanko Ventosa": "Ventosa",
    "Bernardo Bianquetti": "Bianquetti",
    "Carrasco Hidalgo": "Hidalgo",
    "Rammrez Gandullo": "Gandullo",
    "Zubizarreta Urreta": "Zubizarreta",
    "Zuvirma Rodrmguez": "Zuvirma",
    "Sanchez Felip": "Felip",
    "Sanchez Felipe": "Felipe",
    "Bakero Escudero": "Bakero",
    "Begiristain Mujika": "Begiristain",
    "Sanchms Hontiyuelo": "Sanchms",
    "Porlan Noguera": "Porlan",
    "de Souza": "Elber",
    "Julio Villa": "Villa",
    Rep: "Rep  ",
    Six: "Six  ",
    Sosa: "Sosa ",
    Rice: "Rice ",
  },
  86: {},
  88: {
    "Rhoades-Brown": "Rhoades",
    "Julio Alberto": "Alberto",
    "Gsmez Colomer": "Gsmez",
    "Arteche Gsmez": "Gsmez",
    "Martmn Vazquez": "Vazquez",
    "Romero Insfran": "Insfran",
    "Parra Fernandez": "Fernandez",
    "Asprilla Hinestroza": "Asprilla",
    "Poyet Dominguez": "Poyet",
    "Lspez Lspez": "Lopez",
  },
  90: {
    "da Silva": "Carlos",
    "Gomes Raymundo": "Gomes",
    "Fernandes Miranda": "Miranda",
    "Fernandez Bonillo": "Bonillo",
    "Gil Soares de Barros": "Barros",
    "O'Shaughnessy": "O'Shaughnesy",
    "Van Den Hauwe": "v. Den Hauwe",
    "van Breukelen": "v. Breukelen",
    Porterfield: "Porterfield ",
    Dumitrescu: "Dumitrescu ",
    Prosinecki: "Prosinecki ",
    Butragueqo: "Butragueqo ",
    Belodedici: "Belodedici  ",
    Mihajlovic: "Mihajlovic  ",
    Haslegrave: "Law",
    Schumacher: "Schumacher",
    McLintock: "McLintock",
    Shreeves: "Shreeves ",
    Donachie: "Miller",
    Stringer: "Stringer ",
    Venables: "Venables ",
    Docherty: "Docherty  ",
    Appleton: "Apleton",
    Littbarski: "Littbarski ",
    Allardyce: "Allardyce   ",
  },
  98: {},
};

const COMMON_NAME_CHANGES: Record<string, string> = {
  Solskjfr: "Solskjaer",
  Matthdus: "Matthaus",
  "Pfl|gler": "Pflugler",
  "M|ller": "Muller",
  Mvller: "Muller",
  Kvpke: "Kopke",
  "J|rgen": "Jurgen",
  Hd_ler: "Hassler",
  Vvller: "Voller",
  Mxlby: "Molby",
  Hvttges: "Hottges",
  Jsnsson: "Jonsson",
  Sscrates: "Socrates",
  Cafz: "Cafu",
  Hysin: "Hysen",
};

export const getNormalisedName = (name: string, year: number): string =>
  FIRST_NAMES[year][name] || COMMON_NAME_CHANGES[name] || name;
export const getNormalisedSurname = (name: string, year: number): string =>
  SURNAMES[year][name] || COMMON_NAME_CHANGES[name] || name;
export const getNormalisedClub = (name: string): string => NORMALISED_CLUBS[name] || name;

export const getNames = (
  year: number,
  player: Staff,
  firstNames: Names[],
  surnames: Names[],
  commonNames: Names[],
  nation: string,
): { firstName: string; surname: string } => {
  const firstName = getText(firstNames[player.FirstName].name);
  const surname = getText(surnames[player.SecondName].name);
  const commonName = player.CommonName > 0 ? getText(commonNames[player.CommonName].name) : null;

  // Let Brazilian players have a single name
  if (nation === "Brazil" && commonName && commonName.split(" ").length === 1)
    return { firstName: "..", surname: getNormalisedName(commonName, year) };

  return {
    firstName: getNormalisedName(
      commonName && surname !== commonName ? commonName : firstName,
      year,
    ),
    surname: getNormalisedSurname(surname, year),
  };
};
