const UNKNOWN_8: { [key: string]: string | number } = {
  "Aston Villa": "0f",
  "Man Utd": 10,
  Norwich: 10,
  "Sheff Wed": "0d",
  Coventry: "0b",
  Blackburn: "0b",
  "Q.P.R.": "0c",
  Ipswich: 7,
  Tottenham: "0a",
  "Man City": 9,
  Arsenal: "0e",
  Chelsea: "0a",
  Southampton: 1,
  Leeds: 8,
  Liverpool: 8,
  Wimbledon: "0f",
  Everton: 6,
  "West Ham": 3,
  "Sheff Utd": 6,
  Newcastle: "0f",
  Middlesboro: "0c",
  Oldham: "0f",
  "N.Forest": 4,
  "C.Palace": 10,
  Millwall: 7,
  Swindon: 4,
  Portsmouth: "0b",
  Tranmere: "0b",
  Birmingham: 6,
  Leicester: "0a",
  Derby: "0b",
  Wolves: 9,
  Charlton: "0d",
  Bolton: "0d",
  Southend: 6,
  Barnsley: "0b",
  "W.B.A.": "0b",
  Sunderland: 8,
  "Notts C": 6,
  Stoke: "0f",
  Luton: 7,
  "Bristol C": 6,
  Brentford: 7,
  Peterboro: 9,
  "Bristol R": 5,
  Grimsby: "0d",
  Blackpool: "0c",
  "Port Vale": "0e",
  Stockport: 6,
  Cardiff: "0c",
  Oxford: 7,
  York: "0c",
  Rotherham: 5,
  Watford: 8,
  Burnley: 9,
  Bradford: 7,
  Reading: 7,
  Hull: 9,
  Swansea: 7,
  Bournemouth: "0a",
  Plymouth: 8,
  Hartlepool: 4,
  Fulham: 9,
  Preston: 6,
  Exeter: "0a",
  Colchester: 8,
  Cambridge: 6,
  Scunthorpe: 6,
  Chester: 3,
  Huddersfld: 5,
  Barnet: "0c",
  Brighton: 6,
  "Leyton O": "0b",
  Wrexham: "0c",
  Torquay: "0d",
  Doncaster: 9,
  Scarborough: 4,
  Crewe: "0b",
  Rochdale: 5,
  Wycombe: 8,
};

const UNKNOWN_10: { [key: string]: string | number } = {
  "Aston Villa": "b8",
  "Man Utd": "e0",
  Norwich: "c4",
  "Sheff Wed": "a0",
  Coventry: "dc",
  Blackburn: 10,
  "Q.P.R.": "dc",
  Ipswich: "e8",
  Tottenham: "c4",
  "Man City": "c4",
  Arsenal: "94",
  Chelsea: "c4",
  Southampton: "e8",
  Leeds: "b8",
  Liverpool: "a0",
  Wimbledon: 14,
  Everton: "d0",
  "West Ham": "dc",
  "Sheff Utd": "e8",
  Newcastle: "58",
  Middlesboro: "00",
  Oldham: 20,
  "N.Forest": "00",
  "C.Palace": "00",
  Millwall: "00",
  Swindon: "00",
  Portsmouth: "00",
  Tranmere: "0e",
  Birmingham: "00",
  Leicester: "00",
  Derby: "b8",
  Wolves: "00",
  Charlton: "00",
  Bolton: "00",
  Southend: "00",
  Barnsley: "00",
  "W.B.A.": "00",
  Sunderland: "00",
  "Notts C": "00",
  Stoke: "00",
  Luton: "00",
  "Bristol C": "00",
  Brentford: "00",
  Peterboro: "00",
  "Bristol R": "00",
  Grimsby: "00",
  Blackpool: "00",
  "Port Vale": "00",
  Stockport: "00",
  Cardiff: "00",
  Oxford: "00",
  York: "00",
  Rotherham: "00",
  Watford: "00",
  Burnley: "00",
  Bradford: "00",
  Reading: "00",
  Hull: "00",
  Swansea: "00",
  Bournemouth: "00",
  Plymouth: "00",
  Hartlepool: "00",
  Fulham: "00",
  Preston: "00",
  Exeter: "00",
  Colchester: "00",
  Cambridge: "00",
  Scunthorpe: "00",
  Chester: "00",
  Huddersfld: "00",
  Barnet: "00",
  Brighton: "00",
  "Leyton O": "00",
  Wrexham: "00",
  Torquay: "00",
  Doncaster: "00",
  Scarborough: "00",
  Crewe: "00",
  Rochdale: "00",
  Wycombe: "00",
};

export const getUnknown8 = (team: string): string => (UNKNOWN_8[team] || 0).toString();
export const getUnknown10 = (team: string): string => (UNKNOWN_10[team] || 0).toString();
