export const FOREIGN_CLUBS = {
  "8d": "Portugal",
  "8e": "Spain",
  "8f": "France",
  90: "Italy",
  91: "Switzerland",
  92: "Belgium",
  94: "Holland",
  95: "Eire",
  96: "Northern Ireland",
  97: "Germany",
  98: "Austria",
  "9c": "Turkey",
  "9d": "Bulgaria",
  "9e": "Romania",
  "9f": "Hungary",
  a0: "Czech",
  a1: "Poland",
  a2: "Sweden",
  a3: "USSR",
  a4: "Norway",
  a5: "Scotland",
  a6: "Iceland",
  a7: "Finland",
  a8: "Cyprus",
  a9: "Israel",
  aa: "Denmark",
  ab: "",
  ac: "Croatia",
  ad: "Latvia",
  ae: "Zimbabwe",
  af: "Estonia",
  b0: "Bahrain",
  b1: "Canada",
  b2: "South Africa",
  b3: "Russia",
  b4: "Ukraine",
  b5: "Lithuania",
  b6: "Slovenia",
  b7: "Botswana",
  b8: "Cameroon",
  b9: "Nigeria",
  ba: "UAE",
  be: "New Zealand",
  c3: "Ghana",
  c7: "Brazil",
};
